apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-service.fullname" . }}-headless
  labels:
    {{- include "test-service.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "test-service.selectorLabels" . | nindent 4 }}
