{{ if .Values.highlyAvailable }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "test-service.fullname" . }}-monitoring
spec:
  serviceName: {{ include "test-service.fullname" . }}-headless
  replicas: 1
  selector:
    matchLabels:
      {{- include "test-service.selectorLabels" . | nindent 6 }}
      role: monitoring
  template:
    metadata:
      labels:
        {{- include "test-service.selectorLabels" . | nindent 8 }}
        role: monitoring
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values: [{{ include "test-service.name" . }}]
              topologyKey: topology.kubernetes.io/zone
      nodeSelector:
        nodeType: monitoring
      tolerations:
      - effect: NoExecute
        key: nodeType
        operator: Equal
        value: monitoring
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: http
        resources: {{ .Values.resources.monitoring | toYaml | nindent 10 }}
{{- end }}