name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened] 
    branches: [main]

jobs:
  scan-eks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2
      - name: Terraform format check for EKS
        run: terraform fmt -check
        working-directory: ./eks/terraform
      - uses: terraform-linters/setup-tflint@a5a1af8c6551fb10c53f1cd4ba62359f1973746f # v3
        name: Setup tflint
        with:
          tflint_version: v0.45.0
      - name: Init tflint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run tflint for EKS
        run: tflint -f compact
        working-directory: ./eks/terraform
      - name: Run checkov for EKS
        uses: bridgecrewio/checkov-action@a4529b613d94ba07ccbe7c146e8c3dcc8eb386ef # v12.2361.0
        with:
          directory: eks/terraform
          output_format: cli
          output_file_path: console
          quiet: true
          compact: true
  scan-aks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2
      - name: Terraform format check for AKS
        run: terraform fmt -check
        working-directory: ./aks/terraform
      - uses: terraform-linters/setup-tflint@a5a1af8c6551fb10c53f1cd4ba62359f1973746f # v3
        name: Setup tflint
        with:
          tflint_version: v0.45.0
      - name: Init tflint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run tflint for AKS
        run: tflint -f compact
        working-directory: ./aks/terraform
      - name: Run checkov for AKS
        uses: bridgecrewio/checkov-action@a4529b613d94ba07ccbe7c146e8c3dcc8eb386ef # v12.2361.0
        with:
          directory: aks/terraform
          output_format: cli
          output_file_path: console
          quiet: true
          compact: true
  scan-gke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2
      - name: Terraform format check for GKE
        run: terraform fmt -check
        working-directory: ./gke/terraform
      - uses: terraform-linters/setup-tflint@a5a1af8c6551fb10c53f1cd4ba62359f1973746f # v3
        name: Setup tflint
        with:
          tflint_version: v0.45.0
      - name: Init tflint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run tflint for GKE
        run: tflint -f compact
        working-directory: ./gke/terraform
      - name: Run checkov for GKE
        uses: bridgecrewio/checkov-action@a4529b613d94ba07ccbe7c146e8c3dcc8eb386ef # v12.2361.0
        with:
          directory: gke/terraform
          output_format: cli
          output_file_path: console
          quiet: true
          compact: true
  scan-ske:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2
      - name: Terraform format check for SKE
        run: terraform fmt -check
        working-directory: ./ske/terraform
      - uses: terraform-linters/setup-tflint@a5a1af8c6551fb10c53f1cd4ba62359f1973746f # v3
        name: Setup tflint
        with:
          tflint_version: v0.45.0
      - name: Init tflint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run tflint for SKE
        run: tflint -f compact
        working-directory: ./ske/terraform
      - name: Run checkov for SKE
        uses: bridgecrewio/checkov-action@a4529b613d94ba07ccbe7c146e8c3dcc8eb386ef # v12.2361.0
        with:
          directory: ske/terraform
          output_format: cli
          output_file_path: console
          quiet: true
          compact: true