name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  PACKAGE_PREFIX: customer-controlled-region-reference-architectures

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: EKS Release
        uses: montudor/action-zip@v1
        with:
          args: zip -r ${{ env.PACKAGE_PREFIX }}-eks-${{ github.ref_name }}.zip README.md LICENSE eks
      - name: AKS Release
        uses: montudor/action-zip@v1
        with:
          args: zip -r ${{ env.PACKAGE_PREFIX }}-aks-${{ github.ref_name }}.zip README.md LICENSE aks
      - name: GKE Release
        uses: montudor/action-zip@v1
        with:
          args: zip -r ${{ env.PACKAGE_PREFIX }}-gke-${{ github.ref_name }}.zip README.md LICENSE gke
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            ${{ env.PACKAGE_PREFIX }}-eks-${{ github.ref_name }}.zip
            ${{ env.PACKAGE_PREFIX }}-aks-${{ github.ref_name }}.zip
            ${{ env.PACKAGE_PREFIX }}-gke-${{ github.ref_name }}.zip
            