name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: EKS Release
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r sc-private-regions-eks-${{ github.ref_name }}.zip README.md LICENCE eks
      - name: AKS Release
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r sc-private-regions-aks-${{ github.ref_name }}.zip README.md LICENCE aks
      - name: GKE Release
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r sc-private-regions-gke-${{ github.ref_name }}.zip README.md LICENCE gke
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            sc-private-regions-eks-${{ github.ref_name }}.zip
            sc-private-regions-aks-${{ github.ref_name }}.zip
            sc-private-regions-gke-${{ github.ref_name }}.zip
            