name: Terraform Docs

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 4 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Generate terraform-docs for EKS
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # v1.0.0
        with:
          working-dir: ./eks/terraform
          config-file: ./eks/terraform/.terraform-docs.yaml
      - name: Generate terraform-docs for AKS
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # v1.0.0
        with:
          working-dir: ./aks/terraform
          config-file: ./aks/terraform/.terraform-docs.yaml
      - name: Generate terraform-docs for GKE
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # v1.0.0
        with:
          working-dir: ./gke/terraform
          config-file: ./gke/terraform/.terraform-docs.yaml
      - name: Generate terraform-docs for SKE
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # v1.0.0
        with:
          working-dir: ./ske/terraform
          config-file: ./ske/terraform/.terraform-docs.yaml

      - name: Fix permissions
        run: sudo chmod -R ugo+rwX .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5
        with:
          commit-message: Updates to Terraform Docs [automated change]
          title: Automated updates to Terraform Docs
          branch: automated/terraform-docs
          body: |
            Automated updates to Terraform Docs for EKS, AKS, GKE, and SKE