name: Terraform Docs

on:
  workflow_dispatch:
  schedule:
  - cron:  '0 4 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate terraform-docs for EKS
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: ./eks/terraform
          config-file: ./eks/terraform/.terraform-docs.yaml
      - name: Generate terraform-docs for AKS
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: ./aks/terraform
          config-file: ./aks/terraform/.terraform-docs.yaml
      - name: Generate terraform-docs for GKE
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: ./gke/terraform
          config-file: ./gke/terraform/.terraform-docs.yaml
      
      - name: Fix permissions
        run: sudo chmod -R ugo+rwX .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Updates to Terraform Docs [automated change]
          title: Automated updates to Terraform Docs
          branch: automated/terraform-docs
          body: |
            Automated updates to Terraform Docs for EKS, AKS, and GKE